### ISSUE TITLE
Codegen issue while trying to create a fabric component

### ISSUE THREAD

**Issue by PritishSawant** [react-native-community/RNNewArchitectureApp#16]
I am trying to learn fabric. I got it working for most part. 

This is my spec file

```
import type {HostComponent, ViewProps} from 'react-native';
import codegenNativeComponent from 'react-native/Libraries/Utilities/codegenNativeComponent';

interface NativeProps extends ViewProps {
  btnText: string;
}

export default codegenNativeComponent<NativeProps>(
  'SensiView',
) as HostComponent<NativeProps>;

```

It works as expected. I have create a native component on iOS as well. Now I want to assign a clickListener property to my above spec so I did something like below

```
interface NativeProps extends ViewProps {
  btnText: string;
  clickHandler: () => void;
} 
```

As soon as I run `RCT_NEW_ARCH_ENABLED=1 pod install` I get below error

```
[!] Invalid `Podfile` file: [!] /usr/local/bin/node ./../node_modules/react-native/scripts/generate-artifacts.js -p /Users/transformhub/Desktop/NewArchitecture/CapgBtn/ios/.. -o /Users/transformhub/Desktop/NewArchitecture/CapgBtn/ios -e true -c 

[Codegen] Processing react-native core libraries
[Codegen] Found react-native


[Codegen] >>>>> Searching for codegen-enabled libraries in /Users/transformhub/Desktop/NewArchitecture/CapgBtn/node_modules


[Codegen] >>>>> Searching for codegen-enabled libraries in the app
[Codegen] Found capgbtn


[Codegen] >>>>> Processing FBReactNativeSpec
[Codegen] Generated schema: /var/folders/vc/8_1km20d5d3gmxf2w5m8w1180000gn/T/FBReactNativeSpecg51W17/schema.json
[Codegen] Generated artifacts: /Users/transformhub/Desktop/NewArchitecture/CapgBtn/ios/build/generated/ios/FBReactNativeSpec


[Codegen] >>>>> Processing rncore
[Codegen] Generated schema: /var/folders/vc/8_1km20d5d3gmxf2w5m8w1180000gn/T/rncoreX6aoUY/schema.json
[Codegen] Generated artifacts: /Users/transformhub/Desktop/NewArchitecture/CapgBtn/ios/build/generated/ios/react/renderer/components/rncore


[Codegen] >>>>> Processing RNSensiViewSpec


[Codegen] Done.
/Users/transformhub/Desktop/NewArchitecture/CapgBtn/node_modules/react-native-codegen/lib/parsers/typescript/components/props.js:505
      throw new Error(`Unknown prop type for "${name}": "${type}"`);
      ^

Error: Unknown prop type for "clickHandler": "TSFunctionType"
    at getTypeAnnotation (/Users/transformhub/Desktop/NewArchitecture/CapgBtn/node_modules/react-native-codegen/lib/parsers/typescript/components/props.js:505:13)
    at buildPropSchema (/Users/transformhub/Desktop/NewArchitecture/CapgBtn/node_modules/react-native-codegen/lib/parsers/typescript/components/props.js:628:21)
    at /Users/transformhub/Desktop/NewArchitecture/CapgBtn/node_modules/react-native-codegen/lib/parsers/typescript/components/props.js:682:14
    at Array.map (<anonymous>)
    at getProps (/Users/transformhub/Desktop/NewArchitecture/CapgBtn/node_modules/react-native-codegen/lib/parsers/typescript/components/props.js:681:6)
    at buildComponentSchema (/Users/transformhub/Desktop/NewArchitecture/CapgBtn/node_modules/react-native-codegen/lib/parsers/typescript/components/index.js:253:17)
    at buildSchema (/Users/transformhub/Desktop/NewArchitecture/CapgBtn/node_modules/react-native-codegen/lib/parsers/typescript/index.js:164:34)
    at Object.parseFile (/Users/transformhub/Desktop/NewArchitecture/CapgBtn/node_modules/react-native-codegen/lib/parsers/typescript/index.js:210:10)
    at files.reduce.modules (/Users/transformhub/Desktop/NewArchitecture/CapgBtn/node_modules/react-native-codegen/lib/cli/combine/combine-js-to-schema.js:83:30)
    at Array.reduce (<anonymous>)
Error: Command failed: node /Users/transformhub/Desktop/NewArchitecture/CapgBtn/node_modules/react-native-codegen/lib/cli/combine/combine-js-to-schema-cli.js /var/folders/vc/8_1km20d5d3gmxf2w5m8w1180000gn/T/RNSensiViewSpecxw8Vk7/schema.json /Users/transformhub/Desktop/NewArchitecture/CapgBtn/js
/Users/transformhub/Desktop/NewArchitecture/CapgBtn/node_modules/react-native-codegen/lib/parsers/typescript/components/props.js:505
      throw new Error(`Unknown prop type for "${name}": "${type}"`);
      ^

Error: Unknown prop type for "clickHandler": "TSFunctionType"
    at getTypeAnnotation (/Users/transformhub/Desktop/NewArchitecture/CapgBtn/node_modules/react-native-codegen/lib/parsers/typescript/components/props.js:505:13)
    at buildPropSchema (/Users/transformhub/Desktop/NewArchitecture/CapgBtn/node_modules/react-native-codegen/lib/parsers/typescript/components/props.js:628:21)
    at /Users/transformhub/Desktop/NewArchitecture/CapgBtn/node_modules/react-native-codegen/lib/parsers/typescript/components/props.js:682:14
    at Array.map (<anonymous>)
    at getProps (/Users/transformhub/Desktop/NewArchitecture/CapgBtn/node_modules/react-native-codegen/lib/parsers/typescript/components/props.js:681:6)
    at buildComponentSchema (/Users/transformhub/Desktop/NewArchitecture/CapgBtn/node_modules/react-native-codegen/lib/parsers/typescript/components/index.js:253:17)
    at buildSchema (/Users/transformhub/Desktop/NewArchitecture/CapgBtn/node_modules/react-native-codegen/lib/parsers/typescript/index.js:164:34)
    at Object.parseFile (/Users/transformhub/Desktop/NewArchitecture/CapgBtn/node_modules/react-native-codegen/lib/parsers/typescript/index.js:210:10)
    at files.reduce.modules (/Users/transformhub/Desktop/NewArchitecture/CapgBtn/node_modules/react-native-codegen/lib/cli/combine/combine-js-to-schema.js:83:30)
    at Array.reduce (<anonymous>)

    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at executeNodeScript (/Users/transformhub/Desktop/NewArchitecture/CapgBtn/node_modules/react-native/scripts/generate-artifacts.js:81:3)
    at /Users/transformhub/Desktop/NewArchitecture/CapgBtn/node_modules/react-native/scripts/generate-artifacts.js:247:7
    at Array.forEach (<anonymous>)
    at main (/Users/transformhub/Desktop/NewArchitecture/CapgBtn/node_modules/react-native/scripts/generate-artifacts.js:221:15)
    at Object.<anonymous> (/Users/transformhub/Desktop/NewArchitecture/CapgBtn/node_modules/react-native/scripts/generate-artifacts.js:318:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 2f 55 73 65 72 73 2f 74 72 61 6e 73 66 6f 72 6d 68 75 62 2f 44 65 73 6b 74 6f 70 2f 4e 65 77 41 72 63 68 69 74 65 63 74 75 72 65 2f 43 61 70 67 42 74 ... 1533 more bytes>
  ],
  pid: 9170,
  stdout: <Buffer >,
  stderr: <Buffer 2f 55 73 65 72 73 2f 74 72 61 6e 73 66 6f 72 6d 68 75 62 2f 44 65 73 6b 74 6f 70 2f 4e 65 77 41 72 63 68 69 74 65 63 74 75 72 65 2f 43 61 70 67 42 74 ... 1533 more bytes>
}
.

 #  from /Users/transformhub/Desktop/NewArchitecture/CapgBtn/ios/Podfile:13
 #  -------------------------------------------
 #  
 >    use_react_native!(
 #      :path => config[:reactNativePath],
 #  -------------------------------------------

[!] Do not use "pod install" from inside Rosetta2 (x86_64 emulation on arm64).

[!]  - Emulated x86_64 is slower than native arm64

[!]  - May result in mixed architectures in rubygems (eg: ffi_c.bundle files may be x86_64 with an arm64 interpreter)

[!] Run "env /usr/bin/arch -arm64 /bin/bash --login" then try again.

[!] [Codegen] warn: using experimental new codegen integration
```

**Comment by pritsawa** [comment]
@cipolleschi  Do you know how to pass array of strings. I get same error 


```
import type {HostComponent, ViewProps} from 'react-native';
import codegenNativeComponent from 'react-native/Libraries/Utilities/codegenNativeComponent';

interface NativeProps extends ViewProps {
  color: string[];
}

export default codegenNativeComponent<NativeProps>(
  'YourEdgeLinearGradientView',
) as HostComponent<NativeProps>;
```

**Comment by cipolleschi** [comment]
To pass an array of strings, you have to use Readonly arrays. You can find more information in this [section](https://reactnative.dev/docs/next/new-architecture-library-intro#supported-types), both for TypeScript and Flow
